services:
  gh-workflow-cron-trigger:
    image: gh-workflow-cron-trigger
    container_name: gh-workflow-cron-trigger
    env_file:
      - .env
    volumes:
      - "./mounts/config.json:/app/config.json:ro"
